In [22]:
import pandas as pd
#change each file from CSV to xlsx

df = pd.read_csv("data/aos-bordercounties_-_01.10.2020.csv")
df.to_excel("borderStates.xlsx", index=False)

df = pd.read_csv("data/scholars_unders_surveillance_dataset_03-03-2021.csv")
df.to_excel("colleges.xlsx", index=False)

df = pd.read_csv("data/EFF-MuckRock 2016-2017 ALPR DATA.csv")
df.to_excel("alpr.xlsx", index=False)

df = pd.read_csv("data/Atlas of Surveillance-20251114.csv")
df.to_excel("allStates.xlsx", index=False)

In [23]:
#opens the xlsx file 
df1 = pd.read_excel("borderStates.xlsx")
df2 = pd.read_excel("colleges.xlsx")
df3 = pd.read_excel("alpr.xlsx")
df4 = pd.read_excel("allStates.xlsx")

In [24]:
import sqlite3

#creates a database with tables based on our xlsx files
conn = sqlite3.connect("mydatabase.db")

df1.to_sql("borderStates", conn, if_exists="replace", index=False)
df2.to_sql("college", conn, if_exists="replace", index=False)
df3.to_sql("alpr", conn, if_exists="replace", index=False)
df4.to_sql("aos", conn, if_exists="replace", index=False)

15045

In [25]:
#Check to see if everything worked 
pd.read_sql_query("SELECT * FROM college LIMIT 5;", conn)

,Ref,Agency,City,County,State,TypeofLEA,TypeofJuris,Technology,Vendor,Summary,...,Link2Source,Link2Date,Link2DateComment,Link2Type,Link3,Link3Source,Link3Date,Link3DateComment,Link3Type,OtherLinks
0,EDU001,Abraham Baldwin Agricultural College Police De...,Tifton,Tift County,GA,Police,University,Body-worn Cameras,None,The Abraham Baldwin Agricultural College Polic...,...,None,None,None,None,None,None,None,None,None,None
1,EDU002,Agnes Scott College Department of Public Safety,Decatur,DeKalb County,GA,Police,University,Body-worn Cameras,Axon,Police officers with the Agnes Scott College D...,...,None,None,None,None,None,None,None,None,None,None
2,EDU003,Albany State University Police Department,Albany,Dougherty County,GA,Police,University,Body-worn Cameras,None,The Albany State University Police Department ...,...,None,None,None,None,None,None,None,None,None,None
3,EDU004,Arizona State University Police Department,Tempe,Maricopa County,AZ,Police,University,Body-worn Cameras,None,The Arizona State University Police Department...,...,ASU Police Department Facebook page,1/31/2020,None,Social media,None,None,None,None,None,None
4,EDU005,Arkansas State University Police Department,Jonesboro,Craighead County,AR,Police,University,Body-worn Cameras,None,The Arkansas State University Police Departmen...,...,None,None,None,None,None,None,None,None,None,None

In [26]:
#Check to see if everything worked 
pd.read_sql_query("SELECT * FROM borderStates LIMIT 5;", conn)

,RefNo,Agency,City,County,State,LEAType,JurisdictionType,TechnologyType,Vendor,Summary,...,ArchivedAdditionalLink1,AdditionalArchivedLink2,AdditionalArchivedLink3,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28
0,AZCOC010,Cochise County Sheriff's Office,Bisbee,Cochise County,AZ,Sheriff,County,Body-worn Cameras,Axon,The Cochise County Sheriff's office received a...,...,None,None,None,None,None,None,None,None,None,None
1,AZCOC014,Cochise County Sheriff's Office,Bisbee,Cochise County,AZ,Sheriff,County,Camera Network,Cogniac,"In 2016, the Cochise County Sheriff’s Office b...",...,https://www.documentcloud.org/documents/635343...,None,None,None,None,None,None,None,None,None
2,AZCOC001,Cochise County Sheriff's Office,Bisbee,Cochise County,AZ,Sheriff,County,Cell-site Simulators,None,While the Cochise County Sheriff’s Office does...,...,https://www.documentcloud.org/documents/500205...,None,None,None,None,None,None,None,None,None
3,AZCOC012,Cochise County Sheriff's Office,Bisbee,Cochise County,AZ,Sheriff,County,Drones,Lockheed Martin,"In 2014, the Cochise County Sheriff's Office r...",...,None,None,None,None,None,None,None,None,None,None
4,AZCOC003,Cochise County Sheriff's Office,Bisbee,Cochise County,AZ,Sheriff,County,Starchase,Starchase,"In 2012, the Arizona Department of Public Safe...",...,None,None,None,None,None,None,None,None,None,None

In [27]:
#Check to see if everything worked 
pd.read_sql_query("SELECT * FROM alpr LIMIT 5;", conn)

,Agency,State,DirectSharing,NVLS,2016Detections,2016Hits,2017Detections,2017Hits,2016To2017Detections,2016To2017Hits,AllTimeDetections,AllTimeHits,DataSharingLink,2016HitRatioReport,2017HitRatioReport,2016DetectionReport,2016HitReport,2017DetectionReport,2017HitReport,CombinedDetectionHit Data
0,Acworth Police Department,GA,270,Y,Not Provided,Not Provided,Not Provided,Not Provided,Not Provided,Not Provided,None,None,https://www.documentcloud.org/documents/494589...,None,None,None,None,None,None,None
1,Alamo Heights Police Department,TX,14,Y,"1,034",Not Provided,"407,825",Not Provided,"408,859",0,None,None,https://www.documentcloud.org/documents/450163...,https://www.documentcloud.org/documents/455944...,https://www.documentcloud.org/documents/455944...,None,None,None,None,None
2,American Canyon Police Department,CA,27,Y,"786,289",271,"638,034",194,"1,424,323",465,None,None,https://www.documentcloud.org/documents/450164...,https://www.documentcloud.org/documents/455944...,https://www.documentcloud.org/documents/455944...,None,None,None,None,None
3,Atlanta Police Department,GA,8,None,Not Provided,Not Provided,"128,555,383","786,580","128,555,383*","786,580*",None,None,https://www.documentcloud.org/documents/450164...,None,None,None,None,None,None,https://www.documentcloud.org/documents/455944...
4,Auburn Police Department,CA,68,Y,Not Provided,Not Provided,Not Provided,Not Provided,Not Provided,Not Provided,None,None,https://www.documentcloud.org/documents/480202...,None,None,None,None,None,None,None

In [28]:
pd.read_sql_query("SELECT * FROM aos LIMIT 5;", conn)

,AOSNUMBER,City,Counties,County1,County2,County3,County4,County5,County6,County7,...,Link2Source,Link2Type,Link2Date,Link2DateComment,Link3,Link3Snapshot,Link3Source,Link3Type,Link3Date,OtherLinks
0,AOS002987,Anchorage,Anchorage Borough,Anchorage Borough,None,None,None,None,None,None,...,Center for the Study of the Drone at Bard College,,7/12/1905,,https://www.muni.org/Departments/Assembly/Docu...,,www.muni.org,,,
1,AOS004259,Anchorage,Anchorage Borough,Anchorage Borough,None,None,None,None,None,None,...,Electronic Frontier Foundation,,4/7/2014,,https://www.openthegovernment.org/dhs-fusion-c...,,Open the Government,,4/2/2020,
2,AOS006868,Anchorage,Anchorage Borough,Anchorage Borough,None,None,None,None,None,None,...,,,,,,,,,,
3,AOS007456,Anchorage,Anchorage Borough,Anchorage Borough,None,None,None,None,None,None,...,Municipality of Anchorage,,7/21/2009,,https://www.ktuu.com/content/news/Anchorage-po...,,2KTUU,,8/18/2016,
4,AOS013830,Anchorage,Anchorage Borough,Anchorage Borough,None,None,None,None,None,None,...,Alaska's News Source,,8/24/2023,,https://www.anchoragepolice.com/news/body-worn...,,Anchorage Police Department Website,,10/3/2023,

In [29]:
pd.read_sql_query("PRAGMA table_info(aos);", conn)

    cid              name  type  notnull dflt_value  pk
0     0         AOSNUMBER  TEXT        0       None   0
1     1              City  TEXT        0       None   0
2     2          Counties  TEXT        0       None   0
3     3           County1  TEXT        0       None   0
4     4           County2  TEXT        0       None   0
5     5           County3  TEXT        0       None   0
6     6           County4  TEXT        0       None   0
7     7           County5  TEXT        0       None   0
8     8           County6  TEXT        0       None   0
9     9           County7  TEXT        0       None   0
10   10             State  TEXT        0       None   0
11   11            Agency  TEXT        0       None   0
12   12         TypeOfLEA  TEXT        0       None   0
13   13           Summary  TEXT        0       None   0
14   14       TypeOfJuris  TEXT        0       None   0
15   15        Technology  TEXT        0       None   0
16   16            Vendor  TEXT        0       None   0
17   17             Link1  TEXT        0       None   0
18   18     Link1Snapshot  REAL        0       None   0
19   19       Link1Source  TEXT        0       None   0
20   20         Link1Type  TEXT        0       None   0
21   21         Link1Date  TEXT        0       None   0
22   22  Link1DateComment  TEXT        0       None   0
23   23            Link 2  TEXT        0       None   0
24   24     Link2Snapshot  TEXT        0       None   0
25   25       Link2Source  TEXT        0       None   0
26   26         Link2Type  TEXT        0       None   0
27   27         Link2Date  TEXT        0       None   0
28   28  Link2DateComment  TEXT        0       None   0
29   29             Link3  TEXT        0       None   0
30   30     Link3Snapshot  TEXT        0       None   0
31   31       Link3Source  TEXT        0       None   0
32   32         Link3Type  TEXT        0       None   0
33   33         Link3Date  TEXT        0       None   0
34   34        OtherLinks  TEXT        0       None   0

In [30]:
###Our sql version of our 'Technology count for All states' Graph 

sql = "SELECT Technology, COUNT(*) AS Count FROM aos GROUP BY Technology;"

pd.read_sql_query(sql, conn)

                             Technology  Count
0       Automated License Plate Readers   4101
1                     Body-worn Cameras   5334
2                       Camera Registry    770
3                   Cell-site Simulator     91
4                                Drones   1772
5                      Face Recognition    987
6                         Fusion Center     90
7                     Gunshot Detection    258
8                   Predictive Policing    206
9                Real-Time Crime Center    242
10  Third-party Investigative Platforms   1104
11                      Video Analytics     90

In [31]:
#sql version of our 'Technology count from the Police from all states' graph
sql = "SELECT Technology, COUNT(*) AS Count FROM aos WHERE TypeOfLEA = 'Police' GROUP BY Technology;"

pd.read_sql_query(sql, conn)

                             Technology  Count
0       Automated License Plate Readers   3175
1                     Body-worn Cameras   4347
2                       Camera Registry    662
3                   Cell-site Simulator     56
4                                Drones   1080
5                      Face Recognition    699
6                     Gunshot Detection    243
7                   Predictive Policing     98
8                Real-Time Crime Center    183
9   Third-party Investigative Platforms    801
10                      Video Analytics     75

In [32]:
###our sql version of our 'Technology count by Type of Lea' 

#cleans and trims our LEA column 
conn.execute("UPDATE college SET TypeOfLEA = LOWER(TRIM(TypeOfLEA));")
conn.commit()


#groups the data by LEA and technoloy, retrives only the technology, type of LEA, and counts of each 
sql = """ SELECT TypeOfLEA, Technology, COUNT(*) AS count
FROM college
GROUP BY TypeOfLEA, Technology;
"""

pd.read_sql_query(sql, conn)

             TypeofLEA                       Technology  count
0  parking enforcement  Automated License Plate Readers     20
1               police  Automated License Plate Readers     29
2               police                Body-worn Cameras    151
3               police                  Camera Registry      3
4               police                           Drones     10
5               police                 Face Recognition      6
6               police                Gunshot Detection      8
7               police          Social Media Monitoring     21
8               police                  Video Analytics      2
9        public safety                Body-worn Cameras      1

In [33]:
###Our sql version of our 'Technology count for Border States' Graph 

sql = "SELECT TechnologyType, COUNT(*) AS Count FROM borderStates GROUP BY TechnologyType;"

pd.read_sql_query(sql, conn)

                                       TechnologyType  Count
0                             Artificial Intelligence      1
1                     Automated License Plate Readers     34
2      Automated License Plate Readers/Camera Network      1
3   Automated License Plate Readers/Surveillance T...      5
4                                   Body-worn Cameras     50
5                                      Camera Network     14
6             Camera Networks/Real-Time Crime Centers      1
7                                     Camera Registry      2
8                                Cell-site Simulators      3
9                                              Drones     23
10                                   Face Recognition      2
11                                   Face recognition      3
12                                      Fusion Center      2
13                                  Gunshot detection      2
14                            Integrated Fixed Towers      6
15                                      Iris scanning      4
16                                              Lidar      1
17                        Mobile Surveillance Vehicle     14
18                                       Pole Cameras      1
19                                Predictive Policing      1
20                            Real-Time Crime Centers      1
21                  Remote Video Surveillance Systems      7
22                                     Ring/Neighbors      5
23                                 Smart Streetlights      1
24                                          Spy Plane      7
25                                          Starchase      1
26                                Surveillance Towers      2
27                               Surveillance Trailer      1
28                                  Tactical Aerostat      4
29                     Tethered Aerostat Radar System      6
30                          Unattended Ground Sensors      2

In [34]:
###sql version of our 'Technology Type Used by Police in Border States' graph
#our grouped border states grouped by only police, showing the counts of each technology type

sql = "SELECT TechnologyType, COUNT(*) AS Count FROM borderStates WHERE LEAType = 'Police' GROUP BY TechnologyType;"

pd.read_sql_query(sql, conn)

                                       TechnologyType  Count
0                             Artificial Intelligence      1
1                     Automated License Plate Readers     22
2      Automated License Plate Readers/Camera Network      1
3   Automated License Plate Readers/Surveillance T...      4
4                                   Body-worn Cameras     34
5                                      Camera Network      7
6             Camera Networks/Real-Time Crime Centers      1
7                                     Camera Registry      2
8                                Cell-site Simulators      1
9                                              Drones     12
10                                      Fusion Center      1
11                                  Gunshot detection      2
12                        Mobile Surveillance Vehicle      1
13                            Real-Time Crime Centers      1
14                                     Ring/Neighbors      5
15                                 Smart Streetlights      1
16                               Surveillance Trailer      1

In [35]:
#to rename the 2016To2017Detections column so that we can access the column in sql without problems 
conn.execute('ALTER TABLE alpr RENAME COLUMN "2016To2017Detections" TO detections_2016_2017;')
conn.commit()

In [36]:
#to rename the 2016To2017Hits column so that we can access the column in sql without problems 
conn.execute('ALTER TABLE alpr RENAME COLUMN "2016To2017Hits" TO hits_2016_2017;')
conn.commit()

In [37]:
#to check if renaming the column worked/ went through 
pd.read_sql_query("PRAGMA table_info(alpr);", conn)

    cid                       name  type  notnull dflt_value  pk
0     0                     Agency  TEXT        0       None   0
1     1                      State  TEXT        0       None   0
2     2              DirectSharing  TEXT        0       None   0
3     3                       NVLS  TEXT        0       None   0
4     4             2016Detections  TEXT        0       None   0
5     5                   2016Hits  TEXT        0       None   0
6     6             2017Detections  TEXT        0       None   0
7     7                   2017Hits  TEXT        0       None   0
8     8       detections_2016_2017  TEXT        0       None   0
9     9             hits_2016_2017  TEXT        0       None   0
10   10          AllTimeDetections  TEXT        0       None   0
11   11                AllTimeHits  TEXT        0       None   0
12   12            DataSharingLink  TEXT        0       None   0
13   13         2016HitRatioReport  TEXT        0       None   0
14   14         2017HitRatioReport  TEXT        0       None   0
15   15        2016DetectionReport  TEXT        0       None   0
16   16              2016HitReport  TEXT        0       None   0
17   17        2017DetectionReport  TEXT        0       None   0
18   18              2017HitReport  TEXT        0       None   0
19   19  CombinedDetectionHit Data  TEXT        0       None   0

In [38]:
#the sql version of our 

#cleans the data, gets rid of any spaces, dashes, commas, etc from both of the 2016to2017 hits and detections columns
conn.execute("UPDATE alpr SET detections_2016_2017 = REPLACE(REPLACE(REPLACE(detections_2016_2017, ',', ''), ' ', ''), '-', ''), hits_2016_2017       = REPLACE(REPLACE(REPLACE(hits_2016_2017, ',', ''), ' ', ''), '-', '');")
conn.commit()

#converts any values into integer values 
conn.execute("UPDATE alpr SET detections_2016_2017 = CAST(detections_2016_2017 AS INTEGER),hits_2016_2017       = CAST(hits_2016_2017 AS INTEGER);")
conn.commit()

#selects the sumed up ALPR detections from 2016 to 2017 by state, sorted alphabetically 
sql = """SELECT State, SUM(detections_2016_2017) AS TotalDetections
FROM alpr
GROUP BY State
ORDER BY State;
"""

pd.read_sql_query(sql, conn)

   State  TotalDetections
0     AL                0
1     AZ          2154834
2     CA       1135346833
3     CO          6330783
4     CT           478743
5     FL         69994069
6     GA        148860010
7     IA          1358933
8     IL         16525662
9     IN         10174971
10    KS                0
11    LA          1387007
12    MD                0
13    MI          8410004
14    MN           149530
15    MO         50011441
16    NJ         23109521
17    NY        110503544
18    OH         20391950
19    OR           684015
20    PA           462770
21    TX        933833384
22    US            32591
23    WA          1365460

In [39]:
#the sql version of the total ALPR hits from 2016 to 2017, grouped by state and ordered alphabetically 
sql = """SELECT State, SUM(hits_2016_2017) AS TotalHits
FROM alpr
GROUP BY State
ORDER BY State;
"""

pd.read_sql_query(sql, conn)

   State  TotalHits
0     AL          0
1     AZ       5675
2     CA    1488889
3     CO      27888
4     CT        366
5     FL    2715507
6     GA    1051770
7     IA      12425
8     IL      30338
9     IN     266791
10    KS          0
11    LA     161964
12    MD          0
13    MI       6509
14    MN       2269
15    MO    3555683
16    NJ     186682
17    NY      83458
18    OH     287274
19    OR       6176
20    PA        516
21    TX    1492017
22    US          0
23    WA       1967

In [40]:
#Retrives the rows where the county is San Diego, which also includes SDSU
pd.read_sql_query("SELECT * FROM college WHERE County = 'San Diego County';"
, conn)

,Ref,Agency,City,County,State,TypeofLEA,TypeofJuris,Technology,Vendor,Summary,...,Link2Source,Link2Date,Link2DateComment,Link2Type,Link3,Link3Source,Link3Date,Link3DateComment,Link3Type,OtherLinks
0,EDU016,California State University San Marcos Police ...,San Marcos,San Diego County,CA,police,University,Body-worn Cameras,Axon,California State University San Marcos Police ...,...,None,None,None,None,None,None,None,None,None,None
1,EDU112,Palomar College Police Department,San Marcos,San Diego County,CA,police,University,Automated License Plate Readers,None,The Palomar College Police Department began us...,...,None,None,None,None,None,None,None,None,None,None
2,EDU124,San Diego State University Police Department,San Diego,San Diego County,CA,police,University,Automated License Plate Readers,None,The San Diego State University Police Departme...,...,None,None,None,None,None,None,None,None,None,None
3,EDU125,San Diego State University Police Department,San Diego,San Diego County,CA,police,University,Body-worn Cameras,None,The San Diego State University Police Departme...,...,None,None,None,None,None,None,None,None,None,None
4,EDU163,University of California San Diego Police Depa...,La Jolla,San Diego County,CA,police,University,Body-worn Cameras,None,"As of 2020, all University of California, San ...",...,z,5/18/2020,None,Policy,None,None,None,None,None,None
5,EDU164,University of California San Diego Police Depa...,San Diego,San Diego County,CA,police,University,Gunshot Detection,ShotSpotter,The University of California San Diego Police ...,...,None,None,None,None,None,None,None,None,None,None
6,EDU165,University of California San Diego Transportat...,San Diego,San Diego County,CA,parking enforcement,University,Automated License Plate Readers,Park Assist,The University of California San Diego has use...,...,None,None,None,None,None,None,None,None,None,None

In [ ]:
#looks at the Detections and Hits from the San Diego Police Department 
sql = "SELECT Agency, State, detections_2016_2017, hits_2016_2017 FROM alpr WHERE Agency = 'San Diego Police Department';"

#only 0.053% of cars are detected as hot 

pd.read_sql_query(sql, conn)

                        Agency State detections_2016_2017 hits_2016_2017
0  San Diego Police Department    CA               696457            372

In [49]:
#gets the average amount of detections and hits from all of California
sql = "SELECT SUM(detections_2016_2017), SUM(hits_2016_2017) FROM alpr WHERE State = 'CA';"

#only 0.13% of cars detected are cars that are hot 

pd.read_sql_query(sql, conn)

   SUM(detections_2016_2017)  SUM(hits_2016_2017)
0                 1135346833              1488889